name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
      - name: Build
        run: make build
