name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Test
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer
      - name: Test
        run: make test
